app = "livecaller"

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "7000"

[[services]]
  internal_port = 7000
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443
